version: '3.8'

services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1.5G
    ports:
      - "8080:8080"